# Generated by Django 5.2.12 on 2026-04-10 10:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('solar_zone', models.IntegerField(choices=[(1, 'High Solar Potential'), (2, 'Medium Solar Potential'), (3, 'Moderate Solar Potential')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SolarSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size_kw', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('panel_wattage', models.IntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(1000)])),
                ('panel_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('area_m2', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField(help_text='Temperature in Celsius')),
                ('humidity', models.FloatField(help_text='Humidity percentage')),
                ('solar_irradiance', models.FloatField(help_text='Solar irradiance in W/m2')),
                ('wind_speed', models.FloatField(help_text='Wind speed in m/s')),
                ('cloud_cover', models.FloatField(help_text='Cloud cover percentage')),
                ('uv_index', models.FloatField(help_text='UV index')),
                ('season', models.IntegerField(help_text='0=Summer, 1=Monsoon, 2=Winter', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_readings', to='api.location')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('predicted_kwh', models.FloatField()),
                ('actual_kwh', models.FloatField(blank=True, null=True)),
                ('r2_score', models.FloatField(blank=True, null=True)),
                ('rmse', models.FloatField(blank=True, null=True)),
                ('mae', models.FloatField(blank=True, null=True)),
                ('mape', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('granularity', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('monthly', 'Monthly')], default='hourly', max_length=10)),
                ('input_features', models.JSONField(blank=True, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='api.location')),
                ('solar_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='api.solarsystem')),
                ('weather', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='api.weatherreading')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EnergyReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('produced_kwh', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('consumed_kwh', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('net_exported_kwh', models.FloatField(default=0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_readings', to='api.location')),
                ('solar_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_readings', to='api.solarsystem')),
                ('weather', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='energy_readings', to='api.weatherreading')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
